### ISSUE TITLE
Not working with Create 6.0.6

### ISSUE THREAD

**Issue by Aspenpaw** [DrMango14/Create-The_Factory_Must_Grow#189]
Looking back through previous issue reports on this mod it does look like it was working in previous version of update 6 but I'm currently using 6.0.6 and the game crashes on startup, typical java.lang.NoClassDefFoundError stuff.

**Comment by NovaLynxie** [comment]
Weird, I've been able to use this version just fine on Create 6. Assuming you're using Forge 1.20.1 as your modloader.
Are you perhaps using the latest version of TFMG? Latest right now is 0.9.3b which should work with Create 6.

**Comment by Aspenpaw** [comment]
Oop, I installed the latest _release_, not the latest beta. I was using 0.9.3, not 0.9.3b. All ok! :)
